export const STORY_LIST_REQUEST = 'STORY_LIST_REQUEST';
export const STORY_LIST_SUCCESS = 'STORY_LIST_SUCCESS';
export const STORY_LIST_FAIL = 'STORY_LIST_FAIL';

export const STORY_DETAILS_REQUEST = 'STORY_DETAILS_REQUEST';
export const STORY_DETAILS_SUCCESS = 'STORY_DETAILS_SUCCESS';
export const STORY_DETAILS_FAIL = 'STORY_DETAILS_FAIL';

export const STORY_DELETE_REQUEST = 'STORY_DELETE_REQUEST';
export const STORY_DELETE_SUCCESS = 'STORY_DELETE_SUCCESS';
export const STORY_DELETE_FAIL = 'STORY_DELETE_FAIL';

export const STORY_CREATE_REQUEST = 'STORY_CREATE_REQUEST';
export const STORY_CREATE_SUCCESS = 'STORY_CREATE_SUCCESS';
export const STORY_CREATE_FAIL = 'STORY_CREATE_FAIL';
export const STORY_CREATE_RESET = 'STORY_CREATE_RESET';

export const STORY_UPDATE_REQUEST = 'STORY_UPDATE_REQUEST';
export const STORY_UPDATE_SUCCESS = 'STORY_UPDATE_SUCCESS';
export const STORY_UPDATE_FAIL = 'STORY_UPDATE_FAIL';
export const STORY_UPDATE_RESET = 'STORY_UPDATE_RESET';

export const STORY_LIST_MY_REQUEST = 'STORY_LIST_MY_REQUEST'
export const STORY_LIST_MY_SUCCESS = 'STORY_LIST_MY_SUCCESS'
export const STORY_LIST_MY_FAIL = 'STORY_LIST_MY_FAIL'
export const STORY_LIST_MY_RESET = 'STORY_LIST_MY_RESET'

export const STORY_CREATE_COMMENT_REQUEST = 'STORY_CREATE_COMMENT_REQUEST';
export const STORY_CREATE_COMMENT_SUCCESS = 'STORY_CREATE_COMMENT_SUCCESS';
export const STORY_CREATE_COMMENT_FAIL = 'STORY_CREATE_COMMENT_FAIL';
export const STORY_CREATE_COMMENT_RESET = 'STORY_CREATE_COMMENT_RESET';

export const STORY_BY_USER_REQUEST = 'STORY_BY_USER_REQUEST';
export const STORY_BY_USER_SUCCESS = 'STORY_BY_USER_SUCCESS';
export const STORY_BY_USER_FAIL = 'STORY_BY_USER_FAIL';

export const STORY_TOP_REQUEST = 'STORY_TOP_REQUEST';
export const STORY_TOP_SUCCESS = 'STORY_TOP_SUCCESS';
export const STORY_TOP_FAIL = 'STORY_TOP_FAIL';